name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # See where we are and if settings.gradle exists
      - name: Debug: list repo + locate settings.gradle
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "Searching for settings.gradle..."
          find . -type f -name settings.gradle -print

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # Install the exact SDK bits Gradle needs
      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      # Use a hosted Gradle (no wrapper jar needed)
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Auto-detect the project dir (folder containing settings.gradle)
      - name: Build debug APK
        run: |
          PROJ_DIR="$(dirname "$(find . -type f -name settings.gradle | head -n1)")"
          echo "Project directory: $PROJ_DIR"
          if [ -z "$PROJ_DIR" ]; then
            echo "ERROR: Could not find settings.gradle" >&2
            exit 1
          fi
          cd "$PROJ_DIR"
          gradle --version
          gradle assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: "**/app/build/outputs/apk/debug/*.apk"
