name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify project layout
        run: |
          ls -la
          test -f settings.gradle || (echo "settings.gradle missing" && exit 1)
          test -f build.gradle || (echo "build.gradle missing" && exit 1)
          test -f app/build.gradle || (echo "app/build.gradle missing" && exit 1)

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Build (verbose)
        run: |
          set -o pipefail
          gradle --version | tee gradle-info.txt
          gradle assembleDebug --stacktrace --info | tee build-log.txt

      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            gradle-info.txt
            build-log.txt

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
