name: Build Android APK

on:
  workflow_dispatch:   # lets you run it manually
  push:
    branches: [ main ] # runs on push too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: yes | sdkmanager --licenses
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
