name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "Searching for settings.gradle..."
          find . -maxdepth 4 -type f -name "settings.gradle" -print

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build debug APK
        id: build
        shell: bash
        run: |
          set -euo pipefail
          PROJ_DIR="$(pwd)"
          echo "Project dir: $PROJ_DIR"
          if [ -x "./gradlew" ]; then
            GRADLE="./gradlew"
            chmod +x ./gradlew
          else
            GRADLE="gradle"
          fi
          "$GRADLE" --version
          "$GRADLE" assembleDebug --stacktrace --no-daemon
          APK_PATH=$(find "$PWD" -path "*/app/build/outputs/apk/debug/*.apk" | head -n1 || true)
          if [ -z "$APK_PATH" ]; then
            echo "ERROR: APK not found after build."
            find app/build -maxdepth 5 -type f | sed 's/^/ - /' || true
            exit 1
          fi
          echo "apk_path=$APK_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: ${{ steps.build.outputs.apk_path }}
          if-no-files-found: error
