name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Find the folder that contains settings.gradle and expose it as an output
      - name: Locate project dir
        id: probe
        run: |
          PROJ_DIR="$(dirname "$(find . -type f -name settings.gradle | head -n1)")"
          echo "proj_dir=$PROJ_DIR" >> "$GITHUB_OUTPUT"
          echo "Found project dir: $PROJ_DIR"
          test -n "$PROJ_DIR"

      - name: Build debug APK
        working-directory: ${{ steps.probe.outputs.proj_dir }}
        run: |
          gradle --version
          gradle assembleDebug --stacktrace --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: ${{ steps.probe.outputs.proj_dir }}/app/build/outputs/apk/debug/*.apk
